name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    paths: ['Dockerfile']
  pull_request:
    branches: [ "main" ]
    paths: ['Dockerfile']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 #v4.2.0

    - if: github.ref_name == github.event.repository.default_branch
      name: Build and push
      uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 #v6.9.0
      with:
        context: .
        push: true
        tags: $IMAGE:latest,$IMAGE:$GITHUB_SHA

    - if: github.ref_name != github.event.repository.default_branch
      name: Build and push
      uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 #v6.9.0
      with:
        context: .
        push: true
        tags: $IMAGE:$GITHUB_SHA
