name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    paths: ['Dockerfile']
  pull_request:
    branches: [ "main" ]
    paths: ['Dockerfile']

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Set image name to lowercase
      id: img-name
      run: |
        echo "image_name=ghcr.io/${GITHUB_REPOSITORY,,}" >>${GITHUB_OUTPUT}

    - if: github.ref_name == github.event.repository.default_branch
      permissions:
        packages: write
      name: Build and push
      uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 #v6.9.0
      with:
        push: true
        tags: ${{ steps.img-name.outputs.image_name }}:latest,${{ steps.img-name.outputs.image_name }}:${{ github.sha }}

    - if: github.ref_name != github.event.repository.default_branch
      permissions:
        packages: write
      name: Build and push
      uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 #v6.9.0
      with:
        push: true
        tags: ${{ steps.img-name.outputs.image_name }}:${{ github.sha }}
