name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: rust:1.81-alpine3.20

    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 #v4.2.0

    - name: Install deps
      run: apk add --no-cache pcsc-lite-dev musl-dev

    - name: Build
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --all-features --verbose

    - name: Audit
      run: |
        cargo install --version 0.20.1 cargo-audit
        cargo audit

    - name: Lint
      run: cargo clippy -- -D warnings
