name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_IMAGE_NAME }}:latest

    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 #v4.2.0

    - name: Build
      run: cargo build --all-features --verbose

    - name: Run tests
      run: cargo test --all-features --verbose

    - name: Audit
      run: cargo audit

    - name: Check rust version in Cargo.toml
      run: cargo msrv verify -- cargo check --all-features --tests

    - name: Lint
      run: cargo clippy -- -D warnings

    - name: Build release
      run: cargo build --release --verbose
